sudo: false
language: c

addons:
  apt:
    packages:
      - libgtk-3-dev
      - at-spi2-core

before_install:
  - export DISPLAY=":99.0"
  - sh -e /etc/init.d/xvfb start

script:
  - make -C src -j 4
  - ./bin/lint-all
  - ./bin/run-all-specs

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/00cfd309668579417fec
