language: c

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update
  - sudo apt-get install luarocks
  - sudo apt-get install libgtk-3-dev
  - sudo luarocks install busted

install:
  - (cd src && make -j 4)

script: "./bin/howl-spec && ./bin/howl-spec bundles && ./bin/howl-spec lib/ljglibs/spec"

notifications:
  email:
    on_success: always
    on_failure: always
