trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

container: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.30'

steps:
- displayName: 'Build the Flatpak'
  script: |
    flatpak-builder --repo repo build src/io.howl.Editor.yaml
    flatpak build-bundle repo howl.flatpak io.howl.Editor
- tasks: PublishPipelineArtifact@0
  inputs:
    artifactName: 'howl.flatpak'
    targetPath: 'howl.flatpak'
